// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190420132024_dropAltKey")]
    partial class dropAltKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Infrastructure.Entities.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("developer_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnName("developer_fullname")
                        .HasMaxLength(150);

                    b.Property<string>("Nickname")
                        .HasColumnName("developer_nickname")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("developers");
                });

            modelBuilder.Entity("Infrastructure.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("project_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("project_description")
                        .HasMaxLength(450);

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("project_end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("project_name")
                        .HasMaxLength(150);

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("project_start_date");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("Infrastructure.Entities.ProjectDeveloper", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnName("project_id");

                    b.Property<int>("DeveloperId")
                        .HasColumnName("developer_id");

                    b.HasKey("ProjectId", "DeveloperId");

                    b.HasIndex("DeveloperId");

                    b.ToTable("project_developer");
                });

            modelBuilder.Entity("Infrastructure.Entities.ProjectDeveloper", b =>
                {
                    b.HasOne("Infrastructure.Entities.Developer", "Developer")
                        .WithMany("ProjectDevelopers")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Infrastructure.Entities.Project", "Project")
                        .WithMany("ProjectDevelopers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
